### ISSUE TITLE
Meta Training - View Layer

### ISSUE THREAD

**Issue by PPetka** [valis-organization/stretchy#50]
List View
- [ ] make a list of meta trainings, those should have only basic meta training information
- [ ] items should be removable, editable, copyable
- [ ] floating action bar moves you to meta-trainig creation screen

Create meta training view
- [ ] floating action bar that moves you to "pick training screen" 
- [ ] after picking trainings they are shown on the list
- [ ] there is a save button on the bottom
- [ ] "Picking training screen" should allow to pick (elevate or make trainings colorfull) trainings that are all the trainings available (excluding added one)
